# Generated by Django 4.2.5 on 2023-10-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listing_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
