# Generated by Django 4.2.5 on 2023-10-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
