# Generated by Django 4.2.5 on 2023-10-02 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
